apiVersion: v2
name: orion-server
description: Prefect orion application bundle
type: application
home: https://github.com/PrefectHQ
version: 0.0.1
appVersion: "latest"
maintainers:
  - name: gabcoyne
    email: george@prefect.io
sources:
  - https://github.com/PrefectHQ/prefect-recipes
dependencies:
- name: postgresql
  version: "~11.6.0"
  repository: https://charts.bitnami.com/bitnami
  condition: api.postgresql.useSubChart