---
fail_fast: true

repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.0.1
    hooks:
      - id: check-added-large-files
      - id: check-ast
      - id: check-toml
      - id: check-merge-conflict
      - id: check-json
      - id: check-symlinks
      - id: check-vcs-permalinks
      - id: check-yaml
        exclude: "prefect-v1-legacy/devops/monitoring/prefect-prometheus/templates/.*"
        args:
          - --allow-multiple-documents
      - id: detect-aws-credentials
      - id: detect-private-key

  - repo: https://github.com/adrienverge/yamllint.git
    rev: v1.28.0
    hooks:
      - id: yamllint
        exclude: |
            (?x)^(
                prefect-v1-legacy/devops/monitoring/prefect-prometheus/Chart.yaml|
                prefect-v1-legacy/devops/monitoring/prefect-prometheus/templates/.*|
                mkdocs.yml
            )$

  - repo: https://github.com/gruntwork-io/pre-commit
    rev: v0.1.17
    hooks:
      - id: helmlint

  - repo: https://github.com/antonbabenko/pre-commit-terraform
    rev: v1.62.3
    hooks:
      - id: terraform_fmt
      - id: terraform_validate
      - id: terraform_docs
        args:
          - "--args=--config=.terraform-docs.yaml"

  - repo: https://github.com/ambv/black
    rev: 22.3.0
    hooks:
      - id: black
        language_version: python3

  - repo: https://github.com/charliermarsh/ruff-pre-commit
    rev: 'v0.0.254'
    hooks:
      - id: ruff

  - repo: https://github.com/pycqa/isort
    rev: 5.12.0
    hooks:
      - id: isort
        language_version: python3

  - repo: https://github.com/pycqa/flake8
    rev: 4.0.1
    hooks:
      - id: flake8

  - repo: https://github.com/econchick/interrogate
    rev: 1.5.0
    hooks:
      - id: interrogate
        args: [-vv]
        pass_filenames: false

  - repo: https://github.com/fsouza/autoflake8
    rev: v0.3.2
    hooks:
      - id: autoflake8
        language_version: python3
        args: ['--in-place']
