apiVersion: v2
name: orion-agent
description: Prefect orion application bundle
type: application
home: https://github.com/PrefectHQ
version: 0.0.0
appVersion: "latest"
maintainers:
  - name: gabcoyne
    email: george@prefect.io
sources:
  - https://github.com/PrefectHQ/prefect-recipes