# prefectLabels defines what scheduling labels (not K8s labels) should
# be associated with the agent
prefectLabels: []

# jobTemplateFilePath defines which template to use for the agent's jobs. Defaults
# to an empty string, which will use the default template.
# reference: https://docs.prefect.io/orchestration/agents/kubernetes.html#custom-job-template
jobTemplateFilePath: ""

prefectBackend: cloud

# Prefect API, defaults to prefect cloud
prefectApi: https://api.prefect.io


rbacEnabled: true

# Prefect Service Account API key
prefectApiKey: ""

imagePullSecrets: []
# image configures the container image for the agent deployment
image:
  name: prefecthq/prefect
  tag: latest
  pullPolicy: Always
  pullSecrets: []
  # - name: "secret_name"


labels: {}
annotations: {}
podAnnotations: {}
replicas: 1
strategy: {}
podSecurityContext: {}
securityContext: {}
env: []
nodeSelector: {}
tolerations: []
affinity: {}

# resources defines the computational resources for the Prefect Agent
resources:
  limits:
    cpu: 100m
    memory: 128Mi

# job configures values associated with jobs the agent launches
job:
  # resources defines the computational resources for flow jobs
  resources:
    limits:
      memory: ""
      cpu: ""
    requests:
      memory: ""
      cpu: ""

  # imagePullPolicy configures the image pull policy for the flow job
  imagePullPolicy: ""

  # imagePullSecrets defines image pull secrets for the flow job
  # NOTE: These secrets are not merged with the global imagePullSecrets
  imagePullSecrets: []
  # - "secret_name"

serviceAccount:
# create specifies whether a service account should be created to be
# associated with the prefect-server infrastructure
  create: true


  annotations: {}

  # name sets the name of the service account to use
  # If not set and create is true, a name is generated using the
  # prefect-server.nameField template
  name: null

