name: PR Review Reminder

on:
  schedule:
    - cron: "0 19 * * 1-5" # M-F @ 2pm CST
  workflow_dispatch:

jobs:
  remind-reviewer:
    runs-on: ubuntu-latest
    steps:
      - run: echo Sending reminder to requested reviewers.
      - uses: davideviolante/pr-reviews-reminder-action@v1.5.1
        env:
            GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
            webhook-url: ${{ secrets.SLACK_WEBHOOK_RECIPES_CHANNEL }}
            provider: 'slack'
            channel": '#recipes-pr-notifications-sandbox'
      - run: echo Reminder sent!
