name: 🐍 Python Checks 🧹

on:
  pull_request

jobs:
  python-checks:
    name: 💻 Python Checks 🧹
    runs-on: ubuntu-latest
    steps:
      - name: 🛎️ Checking Out Code 📂
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: 🔍 Finding Changed Python Files 📝
        id: changed-python-files
        uses: tj-actions/changed-files@v35
        with:
          files: |
            **/*.py

      - name: 🕵️‍♀️ Output changed Python files
        id: check-python-changes
        run: echo "::set-output name=changed::$(test -n '${{ steps.changed-python-files.outputs.all_changed_files }}')"

      - name: 🐍 Setting Up Python Environment 💻
        uses: actions/setup-python@v4
        with:
          python-version: "3.8"

      - name: Install pre-commit
        run: |
          python -m pip install --upgrade pip
          pip install pre-commit
          
      - name: 🧹 Run pre-commit 🧹
        run: |
          pre-commit run --show-diff-on-failure --color=always --all-files