name: python

on:
  pull_request

jobs:
  python-checks:
    name: python checks
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@v3.3.0

      - name: Get list of changed Python files
        id: changed-files
        run: |
          echo ::set-output name=files::$(git diff --name-only HEAD $(git merge-base HEAD main) | grep ".py$")

      - name: black
        uses: rickstaa/action-black@v1
        if: steps.changed-files.outputs.files != ''
        with:
          args: --check --diff --target=$(echo ${{ steps.changed-files.outputs.files }} | tr '\n' ' ')
          fail_on_error: true

      - name: setup python environment
        uses: actions/setup-python@v1
        with:
          python-version: "3.8"

      - name: flake8 lint
        uses: py-actions/flake8@v2
        with:
          ignore: "E731,W503"