name: 🐍 Python Checks 🧹

on:
  pull_request

jobs:
  python-checks:
    name: 💻 Python Checks 🧹
    runs-on: ubuntu-latest
    steps:
      - name: 🛎️ Checking Out Code 📂
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: 🔍 Finding Changed Python Files 📝
        id: changed-python-files
        uses: tj-actions/changed-files@v35
        with:
          files: |
            **/*.py
            
      - name: 🐍 Setting Up Python Environment 💻
        uses: actions/setup-python@v4
        with:
          python-version: "3.8"
      
      - name: Install black
        run: pip install black

      - name: 🖋️ Run Black Code Formatter on Changed Python Files 💻
        run: |
          black --check ${{ steps.changed-python-files.outputs.all_changed_files }}

      - name: 🔍 Flake8 Linting 💻
        uses: py-actions/flake8@v2
        if: steps.changed-files.outputs.any_changed != ''
        with:
          files: ${{ steps.changed-python-files.outputs.all_changed_files }}
          ignore: "E731,W503"
