name: 🐍 Python Checks 🧹

on:
  pull_request

jobs:
  python-checks:
    name: 💻 Python Checks 🧹
    runs-on: ubuntu-latest
    steps:
      - name: 🛎️ Checking Out Code 📂
        uses: actions/checkout@v3.3.0
        with:
          ref: ${{ github.head_ref }}

      - name: 🔍 Finding Changed Python Files 📝
        id: changed-files
        run: |
          echo ::set-output name=files::$(git diff --name-only origin/${{ github.base_ref }} origin/${{ github.head_ref }} | grep ".py$")
          echo "💻 Changed Python Files: ${{ steps.changed-files.outputs.files }}"

      - name: 🖋️ Black Code Formatter 💻
        uses: rickstaa/action-black@v1.3.0
        if: steps.changed-files.outputs.files != ''
        with:
          args: --check --diff --target=$(echo ${{ steps.changed-files.outputs.files }} | tr '\n' ' ')
          fail_on_error: true

      - name: 🐍 Setting Up Python Environment 💻
        uses: actions/setup-python@v2
        with:
          python-version: "3.8"

      - name: 🔍 Flake8 Linting 💻
        uses: py-actions/flake8@v2
        if: steps.changed-files.outputs.files != ''
        with:
          files: ${{ steps.changed-files.outputs.files }}
          ignore: "E731,W503"
