name: terraform

on:
  pull_request:
    paths:
      - 'devops/**/*.tf'

jobs:
  terraform-checks:
    name: terraform checks
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@v4

      - name: setup terraform
        uses: hashicorp/setup-terraform@v3
      
      - name: terraform format
        run: terraform fmt -recursive -check
        continue-on-error: false