name: terraform

on:
  pull_request:
    # paths:
    #   - '**.tf'

jobs:
  pre-commit-checks:
    name: pre-commit checks
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@v2

      - name: setup terraform
        uses: hashicorp/setup-terraform@v1
      
      - name: terraform format
        run: terraform fmt -recursive -check
        continue-on-error: false

      - name: validate terraform recipes
        uses: devops-infra/action-terraform-validate@v0.3
        with:
          dir_filter: aws/aws-services